slam_toolbox:
  ros__parameters:
    # Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frames — must match your URDF exactly
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping

    # Sim time
    use_sim_time: true

    # Map settings
    resolution: 0.05
    max_laser_range: 6.0
    map_update_interval: 2.0

    # Movement thresholds before adding new node
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1

    # Scan matching
    use_scan_matching: true
    use_scan_barycenter: true
    throttle_scans: 1

    # Loop closure
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_covariance: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # TF and timing
    transform_publish_period: 0.02
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    stack_size_to_use: 40000000

    debug_logging: false
